# Generated by Django 3.2 on 2022-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220511_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
