# Generated by Django 3.2 on 2022-04-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20220403_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestaff',
            name='total_hours_off_a_day',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True),
        ),
    ]
