# Generated by Django 3.2 on 2022-04-15 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_schedulestaff_total_hours_off_a_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestaff',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.schedule'),
        ),
        migrations.AlterField(
            model_name='schedulestaff',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_payment', models.BooleanField(default=False)),
                ('date_payment', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('schedule_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.schedulestaff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
