# Generated by Django 3.2 on 2022-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20220418_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_money',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
