# Generated by Django 3.2 on 2022-04-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20220421_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='buying_price',
        ),
    ]
