# Generated by Django 3.2 on 2022-05-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_remove_material_buying_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetail',
            old_name='materials',
            new_name='material',
        ),
    ]
