# Generated by Django 3.2 on 2021-12-08 19:12

import apps.uploads.enums
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (apps.uploads.enums.FileState["USED"], "USED"),
                            (apps.uploads.enums.FileState["NEW"], "NEW"),
                            (apps.uploads.enums.FileState["DELETED"], "DELETED"),
                        ],
                        default=apps.uploads.enums.FileState["NEW"],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("file_path", models.FileField(blank=True, max_length=128, null=True, upload_to="")),
                ("thumbnail_path", models.JSONField(null=True)),
                ("size", models.IntegerField(null=True)),
                ("mime_type", models.CharField(blank=True, max_length=128, null=True)),
                ("storage", models.CharField(blank=True, max_length=128, null=True)),
                ("metadata", models.JSONField(null=True)),
                ("ip_address", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name": "Upload File",
                "verbose_name_plural": "Upload Files",
            },
        ),
    ]
