# Generated by Django 3.2 on 2021-12-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["user"], name="uploads_upl_user_id_c2e4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["file_path"], name="uploads_upl_file_pa_535ec8_idx"),
        ),
    ]
