# Generated by Django 3.2 on 2021-12-08 19:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppleAccount",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "apple_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name="Apple user id"),
                ),
                (
                    "email",
                    models.CharField(default=None, max_length=250, null=True, unique=True, verbose_name="Apple email"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppleApp",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("app", models.CharField(blank=True, choices=[("APPLE", "Apple")], max_length=20, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("apple_id_client", models.CharField(blank=True, max_length=200, null=True)),
                ("apple_id_team", models.CharField(blank=True, max_length=200, null=True)),
                ("apple_id_key", models.CharField(blank=True, max_length=200, null=True)),
                ("apple_private_key", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
