# Generated by Django 3.2 on 2021-12-08 19:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verb", models.CharField(max_length=100)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("content", models.CharField(blank=True, max_length=250, null=True)),
                ("template", models.CharField(blank=True, help_text="Message template", max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        default="QUEUED",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True, help_text="Visible to user?")),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("memo", models.CharField(blank=True, help_text="Internal Notes", max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
