# Generated by Django 3.2 on 2021-12-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="notification.category"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="target_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="receiver", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="notificatio_name_dc1453_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user"], name="notificatio_user_id_2120fc_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["created"], name="notificatio_created_f8e0c1_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user", "visible", "is_removed"], name="notificatio_user_id_1606bc_idx"),
        ),
    ]
